name: Push to CodeCommit

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::144831534428:role/MIM_Agentic_AI1
          aws-region: us-east-1

      - name: Configure Git for CodeCommit
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: Push to CodeCommit
        run: |
          git remote add codecommit https://git-codecommit.us-east-1.amazonaws.com/v1/repos/MIM_Agentic_AI
          git push codecommit --mirror
